regular:
  Monday:
    - ['8:30', '16:30']
  Tuesday:
    - ['0:00', '0:01']
  Wednesday:
    - ['8:30', '16:30']
  Thursday:
    - ['0:00', '0:01']
  Friday:
    - ['8:30', '16:30']
  Saturday:
    - ['0:00', '0:01']
  Sunday:
    - ['0:00', '0:01']
holidays:
  - date: [2018-11-21, 2018-11-25]
    reason: Thanksgiving Break
  - date: 2018-12-03
    reason: Late Lab Opening
    hours:
      - ['10:00', '18:00']
  - date: 2018-12-14
    reason: Last Day of Finals
    hours:
      - ['9:00', '14:00']
  - date: [2018-12-15, 2019-01-14]
    reason: Winter Break
  - date: 2019-02-16
    reason: Early Lab Closure
    hours:
      - ['9:00', '18:00']
  - date: 2019-02-18
    reason: Presidents' Day
  - date: 2019-02-19
    reason: Early Lab Closure
    hours:
      - ['9:00', '18:00']
  - date: 2019-02-20
    reason: Early Lab Closure # FAFSA Workshop
    hours:
      - ['9:00', '18:00']
  - date: 2019-02-28
    reason: Early Lab Closure # FAFSA Workshop
    hours:
      - ['9:00', '18:00']
  - date: 2019-03-19
    reason: Early Lab Closure # Cal VSA Resume Workshop
    hours:
      - ['9:00', '19:00']
  - date: [2019-03-23, 2019-03-31]
    reason: Spring Break
  - date: 2019-04-24
    reason: Early Lab Closure # IST Open House
    hours:
      - ['9:00', '15:00']
      - ['18:00', '20:00']
