# Once this file is changed, you'll need to trigger a Puppet run on the
# k8s workers (or whatever is running ocfweb) for the config to propagate to ocfweb.
---

force_lab_closed: false

# please remember: the banner is for urgent announcements!
# consider adding something to the website normally if it's not urgent or you
# plan to leave it there for a while.
banner_visible: true

banner_html: |
  <div class="update-banner" id="banner">
    <h4 id="banner-header">MLK Building Closure/Campus Power Outage, Friday 10/11</h4>
    <p>
        On Friday 10/11 afternoon, power was restored to MLK Student Union building. However, OCF will remain closed for the remainder of the day. We will resume our normal hours starting Saturday, 10/12.
        <br /><br />
        We are working to restore our services as soon as possible. Status updates will be posted to our blog (<a href="https://status.ocf.berkeley.edu">status.ocf.berkeley.edu</a>) as necessary.
    </p>
  </div>
  <style>
    #banner-header, #banner-header-2 {
      font-size: 125%;
    }
    #banner {
      display: block;
      color: black;
      font-size: 100%;
      background-color: #e6b129;
    }
    #banner:hover {
      background-color: #e6b129;
    }
  </style>
